# Generated by Django 3.0.3 on 2020-03-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('problem_statement', models.CharField(max_length=1000)),
                ('event_date', models.DateTimeField()),
                ('people_required', models.IntegerField()),
                ('fees', models.IntegerField()),
                ('rules', models.CharField(max_length=10000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=7)),
                ('college_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.Department')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbapp.Event')),
            ],
        ),
    ]
